# Final Project

In [151]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import linear_model 
from sklearn import metrics
%matplotlib inline

In [152]:
#read in dataset
auto_data = pd.read_csv("Automobile_data.csv")

print(auto_data.shape)
print(type(auto_data))

(205, 26)
<class 'pandas.core.frame.DataFrame'>


In [153]:
#Get rid of garbage values
for i in range(205):
    if auto_data['peak-rpm'][i] == '?':
        auto_data = auto_data.drop([i])
    elif auto_data['horsepower'][i] == '?':
        auto_data = auto_data.drop([i])
    elif auto_data['price'][i] == '?':
        auto_data = auto_data.drop([i])
    else:
        continue

In [154]:
#Convert all string(objects) variables to float
auto_data['peak-rpm'] = auto_data['peak-rpm'].astype(float)
auto_data['horsepower'] = auto_data['horsepower'].astype(float)
auto_data['price'] = auto_data['price'].astype(float)

In [155]:
#Create models
model_1 = linear_model.LinearRegression()
model_1.fit(auto_data[['length', 'width', 'peak-rpm', 'horsepower']], auto_data.price)

model_2 = linear_model.LinearRegression()
model_2.fit(auto_data[['width', 'peak-rpm', 'horsepower']], auto_data.price)

model_3 = linear_model.LinearRegression()
model_3.fit(auto_data[['length','peak-rpm', 'horsepower']], auto_data.price)

model_4 = linear_model.LinearRegression()
model_4.fit(auto_data[['length', 'width', 'horsepower']], auto_data.price)

model_5 = linear_model.LinearRegression()
model_5.fit(auto_data[['length', 'width', 'peak-rpm']], auto_data.price)

print(model_1.coef_)
print(model_2.coef_)
print(model_3.coef_)
print(model_4.coef_)
print(model_5.coef_)

[ 2.87472339e+01  1.28716588e+03 -1.12830178e+00  1.23746840e+02]
[ 1.41284011e+03 -1.21511610e+00  1.25015691e+02]
[187.30028401  -1.47421078 138.43325596]
[  45.1404029  1338.93907941  117.26453449]
[1.35544513e+02 2.26696482e+03 1.76109649e+00]


In [156]:
#Set up cross validation and find SSE/RMSE
X1 = auto_data[['length', 'width', 'peak-rpm', 'horsepower']]
X2 = auto_data[['width', 'peak-rpm', 'horsepower']]
X3 = auto_data[['length','peak-rpm', 'horsepower']]
X4 = auto_data[['length', 'width', 'horsepower']]
X5 = auto_data[['length', 'width', 'peak-rpm']]
Y = auto_data['price']

#Split train and test data
from sklearn.model_selection import train_test_split

In [157]:
#Model 1 SSE and RMSE values
X1_train, X1_test, Y_train, Y_test = train_test_split(X1,Y,test_size=0.2)

model_1_cross = linear_model.LinearRegression()
model_1_cross.fit(X1_train, Y_train)

y_predict = model_1_cross.predict(X1_test)

mod1_RMSE = np.sqrt(metrics.mean_squared_error(Y_test, y_predict))
mod1_SSE = (mod1_RMSE**2)*(40)

print("Model 1 RMSE = " + str(mod1_RMSE))
print("Model 1 SSE = " + str(mod1_SSE))

Model 1 RMSE = 4581.553144803541
Model 1 SSE = 839625168.7463686


In [158]:
#Model 2 SSE and RMSE values
X2_train, X2_test, Y_train, Y_test = train_test_split(X2,Y,test_size=0.2)

model_2_cross = linear_model.LinearRegression()
model_2_cross.fit(X2_train, Y_train)

y_predict = model_2_cross.predict(X2_test)

mod2_RMSE = np.sqrt(metrics.mean_squared_error(Y_test, y_predict))
mod2_SSE = (mod2_RMSE**2)*(40)

print("Model 2 RMSE = " + str(mod2_RMSE))
print("Model 2 SSE = " + str(mod2_SSE))

Model 2 RMSE = 3517.084294966649
Model 2 SSE = 494795277.516042


In [159]:
#Model 3 SSE and RMSE values
X3_train, X3_test, Y_train, Y_test = train_test_split(X3,Y,test_size=0.2)

model_3_cross = linear_model.LinearRegression()
model_3_cross.fit(X3_train, Y_train)

y_predict = model_3_cross.predict(X3_test)

mod3_RMSE = np.sqrt(metrics.mean_squared_error(Y_test, y_predict))
mod3_SSE = (mod3_RMSE**2)*(40)

print("Model 3 RMSE = " + str(mod3_RMSE))
print("Model 3 SSE = " + str(mod3_SSE))

Model 3 RMSE = 3639.9318373709634
Model 3 SSE = 529964151.2282703


In [160]:
#Model 4 SSE and RMSE values
X4_train, X4_test, Y_train, Y_test = train_test_split(X4,Y,test_size=0.2)

model_4_cross = linear_model.LinearRegression()
model_4_cross.fit(X4_train, Y_train)

y_predict = model_4_cross.predict(X4_test)

mod4_RMSE = np.sqrt(metrics.mean_squared_error(Y_test, y_predict))
mod4_SSE = (mod4_RMSE**2)*(40)

print("Model 4 RMSE = " + str(mod4_RMSE))
print("Model 4 SSE = " + str(mod4_SSE))

Model 4 RMSE = 4975.9578953276105
Model 4 SSE = 990406279.0429273


In [161]:
#Model 5 SSE and RMSE values
X5_train, X5_test, Y_train, Y_test = train_test_split(X5,Y,test_size=0.2)

model_5_cross = linear_model.LinearRegression()
model_5_cross.fit(X5_train, Y_train)

y_predict = model_5_cross.predict(X5_test)

mod5_RMSE = np.sqrt(metrics.mean_squared_error(Y_test, y_predict))
mod5_SSE = (mod5_RMSE**2)*(40)

print("Model 5 RMSE = " + str(mod5_RMSE))
print("Model 5 SSE = " + str(mod5_SSE))

Model 5 RMSE = 5144.99475649116
Model 5 SSE = 1058838841.7728612
